<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
<<<<<<< HEAD


        \DB::table('users')->delete();

        \DB::table('users')->insert(array (
            0 =>
            array (
                'id' => 1,
                'name' => 'AdminMaster',
                'first_lastname' => NULL,
                'second_lastname' => NULL,
                'avatar' => NULL,
                'email' => 'admin_master@example.com',
                'username' => 'admin_master@example.com',
                'password' => Hash::make('secret'),
                'rut' => NULL,
                'phone' => NULL,
                'address' => NULL,
                'dob' => NULL,
                'remember_token' => NULL,
                'state' => 1,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now()
            ),
            1 =>
            array (
                'id' => 2,
                'name' => 'AdminInstitution',
                'first_lastname' => NULL,
                'second_lastname' => NULL,
                'avatar' => NULL,
                'email' => 'admin_institution@example.com',
                'username' => 'admin_institution@example.com',
                'password' => '$2y$10$bHEvavv1EnJH2/VqbFHkLepLybN5oz.60/g2izyhZzOeY0GdmjtFy',
                'rut' => NULL,
                'phone' => NULL,
                'address' => NULL,
                'dob' => NULL,
                'remember_token' => NULL,
                'state' => 1,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now()
            ),
            2 =>
            array (
                'id' => 3,
                'name' => 'Student',
                'first_lastname' => NULL,
                'second_lastname' => NULL,
                'avatar' => NULL,
                'email' => 'student@example.com',
                'username' => 'student@example.com',
                'password' => Hash::make('secret'),
                'rut' => NULL,
                'phone' => NULL,
                'address' => NULL,
                'dob' => NULL,
                'remember_token' => NULL,
                'state' => 1,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now()
            ),
            3 =>
            array (
                'id' => 4,
                'name' => 'Professor',
                'first_lastname' => NULL,
                'second_lastname' => NULL,
                'avatar' => NULL,
                'email' => 'professor@example.com',
                'username' => 'professor@example.com',
                'password' => Hash::make('secret'),
                'rut' => NULL,
                'phone' => NULL,
                'address' => NULL,
                'dob' => NULL,
                'remember_token' => NULL,
                'state' => 1,
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now()
            ),
            4 =>
            array (
                'id' => 5,
                'name' => 'Attorney',
                'first_lastname' => NULL,
                'second_lastname' => NULL,
                'avatar' => NULL,
                'email' => 'attorney@example.com',
                'username' => 'attorney@example.com',
                'password' => Hash::make('secret'),
                'rut' => NULL,
                'phone' => NULL,
                'address' => NULL,
                'dob' => NULL,
                'remember_token' => NULL,
                'state' => 1,
                'email_verified_at' => now(),
                'created_at' => '2020-07-09 17:03:28',
                'updated_at' => '2020-07-09 17:03:28',
            ),
            5 =>
            array (
                'id' => 602,
                'name' => 'vilo',
                'first_lastname' => 'vilo',
                'second_lastname' => 'vilo',
                'avatar' => NULL,
                'email' => 'vilo@gmail.com',
                'username' => 'vilo@gmail.com',
                'password' => '$2y$10$9x09RQcDfDwadidi0HYAn.S55A.R5GhZPjsUyV6uCaqPeI2hQ6Zv.',
                'rut' => '11.111.111-1',
                'phone' => '1',
                'address' => NULL,
                'dob' => NULL,
                'remember_token' => NULL,
                'state' => 1,
                'email_verified_at' => NULL,
                'created_at' => '2020-07-09 13:16:50',
                'updated_at' => '2020-07-09 13:16:50',
            ),
            6 =>
            array (
                'id' => 603,
                'name' => 'Edgard',
                'first_lastname' => 'Vilo',
                'second_lastname' => 'Palacios',
                'avatar' => NULL,
                'email' => 'edgard.vilo@maxisoft.cl',
                'username' => 'edgard.vilo@maxisoft.cl',
                'password' => '$2y$10$wSncw3XpF9BT5li.5mPWOOE.ojfJcOxd12m6DTYPHw1V9BFrADaN2',
                'rut' => '17.722.517-7',
                'phone' => '',
                'address' => NULL,
                'dob' => NULL,
                'remember_token' => NULL,
                'state' => 1,
                'email_verified_at' => NULL,
                'created_at' => '2020-07-09 13:16:50',
                'updated_at' => '2020-07-09 13:16:50',
            ),
            7 =>
            array (
                'id' => 604,
                'name' => 'Carolina',
                'first_lastname' => 'Mena',
                'second_lastname' => 'Muñoz',
                'avatar' => NULL,
                'email' => 'carolina@gmail.com',
                'username' => 'carolina@gmail.com',
                'password' => '$2y$10$erZWcw5M.wfWERI4RPKJRe5ts5PzMbraCRHPgv/4OtFluXh3lrUWe',
                'rut' => '15.594.790-k',
                'phone' => '983853719',
                'address' => NULL,
                'dob' => NULL,
                'remember_token' => NULL,
                'state' => 1,
                'email_verified_at' => NULL,
                'created_at' => '2020-07-09 13:16:50',
                'updated_at' => '2020-07-09 13:16:50',
            ),
            8 =>
            array (
                'id' => 605,
                'name' => 'Alvaro',
                'first_lastname' => 'Perez',
                'second_lastname' => '....',
                'avatar' => NULL,
                'email' => 'alvaro@gmail.com',
                'username' => 'alvaro@gmail.com',
                'password' => '$2y$10$sEvQGXtIkG/aJPXrqH7CvuKuz4e1J/cyt.YB6Dsvbdn1ceVjd3vty',
                'rut' => '15.055.798-4',
                'phone' => '9999999',
                'address' => NULL,
                'dob' => NULL,
                'remember_token' => NULL,
                'state' => 1,
                'email_verified_at' => NULL,
                'created_at' => '2020-07-09 13:16:50',
                'updated_at' => '2020-07-09 13:16:50',
            ),
            9 =>
            array (
                'id' => 606,
                'name' => 'Ed',
                'first_lastname' => 'Vi',
                'second_lastname' => 'Pa',
                'avatar' => NULL,
                'email' => 'thevilos@gmail.com',
                'username' => 'thevilos@gmail.com',
                'password' => '$2y$10$O4fwWkqxdGMVIFicLkvVCOAorIzONNyIuEdo2./C4XyyBZKM.9WNC',
                'rut' => '22.222.222-2',
                'phone' => '983853719',
                'address' => NULL,
                'dob' => NULL,
                'remember_token' => NULL,
                'state' => 1,
                'email_verified_at' => NULL,
                'created_at' => '2020-07-09 13:16:50',
                'updated_at' => '2020-07-09 13:16:50',
            ),
            10 =>
            array (
                'id' => 607,
                'name' => 'Victoria',
                'first_lastname' => 'Pérez',
                'second_lastname' => 'Mena',
                'avatar' => NULL,
                'email' => 'carolinamena_profe@hotmail.com',
                'username' => 'carolinamena_profe@hotmail.com',
                'password' => '$2y$10$xWfdZXAKKVqeTwzR4Fq6BuGKog48JSEQBma.4kSdVobCq19P77wpm',
                'rut' => '23.927.748-9',
                'phone' => '989483379',
                'address' => NULL,
                'dob' => NULL,
                'remember_token' => NULL,
                'state' => 1,
                'email_verified_at' => NULL,
                'created_at' => '2020-07-09 13:16:50',
                'updated_at' => '2020-07-09 13:16:50',
            ),
            11 =>
            array (
                'id' => 608,
                'name' => 'sdfsd',
                'first_lastname' => 'sdfsdf',
                'second_lastname' => 'dfgdfg',
                'avatar' => NULL,
                'email' => 'asdasdas@sdfsdf.cl',
                'username' => 'asdasdas@sdfsdf.cl',
                'password' => '$2y$10$TgEgPQehFFak.eY8km6z6.9CYe8mU/.jC0p4JgP/fe54mMjbnrYTG',
                'rut' => '1.234.567-8',
                'phone' => '329482394892',
                'address' => NULL,
                'dob' => NULL,
                'remember_token' => NULL,
                'state' => 1,
                'email_verified_at' => NULL,
                'created_at' => '2020-07-09 13:16:50',
                'updated_at' => '2020-07-09 13:16:50',
            ),
            12 =>
            array (
                'id' => 609,
                'name' => 'Cristhian',
                'first_lastname' => 'Garcia',
                'second_lastname' => 'Rojas',
                'avatar' => NULL,
                'email' => 'cgarcia7@live.cl',
                'username' => 'cgarcia7@live.cl',
                'password' => '$2y$10$y7zWRDkHN.sTU0AJ6Jmb.eQA3Cl.jZj2RwCKhd7afTApQ/WYknDy6',
                'rut' => '18.493.501-5',
                'phone' => '973622316',
                'address' => NULL,
                'dob' => NULL,
                'remember_token' => NULL,
                'state' => 1,
                'email_verified_at' => NULL,
                'created_at' => '2020-07-09 13:16:50',
                'updated_at' => '2020-07-09 13:16:50',
            ),
            13 =>
            array (
                'id' => 610,
                'name' => 'Joaquín',
                'first_lastname' => 'Pérez',
                'second_lastname' => 'Jamett',
                'avatar' => NULL,
                'email' => 'COMERCIALSUPRA4@GMAIL.COM',
                'username' => 'COMERCIALSUPRA4@GMAIL.COM',
                'password' => '$2y$10$LLEAq4K9UAPrnMIQIfpTdOUgpFXYIRRJacI3PvqyNz0FQ12ql5N/.',
                'rut' => '21.015.065-k',
                'phone' => '989483379',
                'address' => NULL,
                'dob' => NULL,
                'remember_token' => NULL,
                'state' => 1,
                'email_verified_at' => NULL,
                'created_at' => '2020-07-09 13:16:50',
                'updated_at' => '2020-07-09 13:16:50',
            ),
            14 =>
            array (
                'id' => 611,
                'name' => 'Gollo',
                'first_lastname' => 'Rodriguez',
                'second_lastname' => 'Arenas',
                'avatar' => NULL,
                'email' => 'gregoriorodriguez@acperforaciones.cl',
                'username' => 'gregoriorodriguez@acperforaciones.cl',
                'password' => '$2y$10$ebGkQD1MsWwv1PCK8xZXVeuOVZuQE/ZeNs/tb./b7OvoODEqAnMau',
                'rut' => '15.908.617-8',
                'phone' => '975399322',
                'address' => NULL,
                'dob' => NULL,
                'remember_token' => NULL,
                'state' => 1,
                'email_verified_at' => NULL,
                'created_at' => '2020-07-09 13:16:50',
                'updated_at' => '2020-07-09 13:16:50',
            ),
            15 =>
            array (
                'id' => 612,
                'name' => 'Julieta',
                'first_lastname' => 'Perez',
                'second_lastname' => 'Mena',
                'avatar' => NULL,
                'email' => 'prof_carolinamena@hotmail.com',
                'username' => 'prof_carolinamena@hotmail.com',
                'password' => '$2y$10$aO9S0oHy7mqdSPDvacNFuekLBVFCkSVSqo/2mmyZYkvIK7HEMunjm',
                'rut' => '25.240.914-9',
                'phone' => '961568413',
                'address' => NULL,
                'dob' => NULL,
                'remember_token' => NULL,
                'state' => 1,
                'email_verified_at' => NULL,
                'created_at' => '2020-07-09 13:16:50',
                'updated_at' => '2020-07-09 13:16:50',
            ),
            16 =>
            array (
                'id' => 613,
                'name' => 'Julieta',
                'first_lastname' => 'Perez',
                'second_lastname' => 'Mena',
                'avatar' => NULL,
                'email' => 'cedin.carolinamena@gmail.com',
                'username' => 'cedin.carolinamena@gmail.com',
                'password' => '$2y$10$iwCFyWGPXB0gpB2.HI9A1eTDKz545znxEIb7Q35VaPEgMRGq0Hq9a',
                'rut' => '25.240.914-7',
                'phone' => '961568413',
                'address' => NULL,
                'dob' => NULL,
                'remember_token' => NULL,
                'state' => 1,
                'email_verified_at' => NULL,
                'created_at' => '2020-07-09 13:16:50',
                'updated_at' => '2020-07-09 13:16:50',
            ),
            17 =>
            array (
                'id' => 614,
                'name' => 'Luis',
                'first_lastname' => 'Cuello',
                'second_lastname' => 'Alfaro',
                'avatar' => NULL,
                'email' => '15055798-4',
                'username' => '15055798-4',
                'password' => '$2y$10$NuRrNjC78amQiBVanlZm.O7R6tJo5RMSLSsbkNl.bcQtkj8EnESaq',
                'rut' => '18.002.988-5',
                'phone' => '+56 9 7470 3979',
                'address' => NULL,
                'dob' => NULL,
                'remember_token' => NULL,
                'state' => 1,
                'email_verified_at' => NULL,
                'created_at' => '2020-07-09 13:16:50',
                'updated_at' => '2020-07-09 13:16:50',
            ),
            18 =>
            array (
                'id' => 615,
                'name' => 'users 1',
                'first_lastname' => 'XXX',
                'second_lastname' => 'XXX',
                'avatar' => NULL,
                'email' => 'AEPL1982@GMAIL.COM',
                'username' => 'AEPL1982@GMAIL.COM',
                'password' => '$2y$10$VFaB3jIdW9AT6bWD/NmT1OOq.7YUiDX.sqTqaf15Qgf9nUvJddrt2',
                'rut' => '9.999.999-9',
                'phone' => '999999999',
                'address' => NULL,
                'dob' => NULL,
                'remember_token' => NULL,
                'state' => 1,
                'email_verified_at' => NULL,
                'created_at' => '2020-07-09 13:16:50',
                'updated_at' => '2020-07-09 13:16:50',
            ),
        ));


=======
        //factory(App\User::class, 20)->create();
        DB::table('users')->insert([
            'name' => 'Admin',
            'email' => 'admin@example.com',
            'username' => 'admin@example.com',
            'email_verified_at' => now(),
            'password' => Hash::make('secret'),
            'created_at' => now(),
            'updated_at' => now()
        ]);
>>>>>>> maintpro
    }
}
