version: "3.8"
services:
  ui:
    container_name: ui
    build: ./ui
    command: npm run serve
    volumes:
      - ./ui:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - api
    stdin_open: true

  api:
    container_name: api
    build: ./api
    working_dir: /var/www/
    volumes:
      - ./api:/var/www

  postgres:
    container_name: postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: portal
      POSTGRES_PASSWORD: password
      POSTGRES_USER: portal_user
      SERVICE_TAGS: dev
      SERVICE_NAME: pgsql
    volumes: 
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - '8080:8080'
      - '443:443'
    volumes:
      - ./api:/var/www
      - ./api/nginx:/etc/nginx/conf.d

volumes:
  postgres_data:

      
